name: SonarCloud Analysis
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for correct issue assignment

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      # CORRECTED BUILD STEP for your folder structure
      # We enter the 'Project' directory so Ant can find build.xml and nbproject/
      - name: Build with Ant
        run: |
          cd Project
          ant

      # SCAN STEP
      # The scanner runs from the root, so it uses the paths defined in sonar-project.properties
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}